apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  POSTGRES_CONNECTION_STRING: SG9zdD1wZ3J1cy1wb3N0Z3Jlc3FsO1VzZXJuYW1lPWFkbWluO1Bhc3N3b3JkPWFkbWluO0RhdGFiYXNlPVVzZXJTZXJ2aWNl
  SECRET: ZmdyeXJoZmRqaGdrbG9zc2RzZnNkZmRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZHNzc3Nzc3Nzc3Nzc3Nzc3Nzc2RzZmRm
