<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BusinessModel\Application\Application.csproj" />
  </ItemGroup>
  <ItemGroup>
		<Protobuf Include="Protos\billing.proto" GrpcServices="Client" />
	    <Protobuf Include="Protos\warehouse.proto" GrpcServices="Client" />
	    <Protobuf Include="Protos\delivery.proto" GrpcServices="Client" />
  </ItemGroup>
</Project>
