networks:
   shop-bridge:
    driver: bridge

services:
  userservise:
    build: ../app/UserServise
    container_name: userservice-service
    image: gabbazovr/userserviselocal:latest
    hostname: userservice-service
    restart: always
    networks:
      - shop-bridge
    depends_on:
      - postgres_db
    environment:
     - POSTGRES_CONNECTION_STRING=Host=postgres_db;Username=postgres;Password=admin;Database=userservise
     - SECRET=fgryrhfdjhgklossdsfsdfdddddddddddddddddddddddddddddddddddddddssssssssssssssssssdsfdf

  apigetway:
    build: ../app/ApiGetway
    image: gabbazovr/apigetwaylocal:latest
    container_name: apigetway-service
    hostname: apigetway-service
    restart: always
    networks:
      - shop-bridge
    depends_on:
      - postgres_db
    environment:
     - POSTGRES_CONNECTION_STRING=Host=postgres_db;Username=postgres;Password=admin;Database=apigetway
     - SECRET=fgryrhfdjhgklossdsfsdfdddddddddddddddddddddddddddddddddddddddssssssssssssssssssdsfdf

  billing:
    build: ../app/Billing
    container_name: billing-service
    image: gabbazovr/billinglocal:latest
    hostname: billing-service
    restart: always
    networks:
      - shop-bridge
    depends_on:
      - postgres_db
      - rabbitmq
    environment:
     - POSTGRES_CONNECTION_STRING=Host=postgres_db;Username=postgres;Password=admin;Database=billing
     - SECRET=fgryrhfdjhgklossdsfsdfdddddddddddddddddddddddddddddddddddddddssssssssssssssssssdsfdf

  notification:
    build: ../app/Notification
    container_name: notification-service
    image: gabbazovr/notificationlocal:latest
    hostname: notification-service
    restart: always
    networks:
      - shop-bridge
    depends_on:
      - postgres_db
    environment:
     - POSTGRES_CONNECTION_STRING=Host=postgres_db;Username=postgres;Password=admin;Database=notification
     - SECRET=fgryrhfdjhgklossdsfsdfdddddddddddddddddddddddddddddddddddddddssssssssssssssssssdsfdf

  order:
    build: ../app/Order
    container_name: order-service
    image: gabbazovr/orderfinal:latest
    hostname: order-service
    restart: always
    networks:
      - shop-bridge
    depends_on:
      - postgres_db
      - rabbitmq
    environment:
     - POSTGRES_CONNECTION_STRING=Host=postgres_db;Username=postgres;Password=admin;Database=order
     - SECRET=fgryrhfdjhgklossdsfsdfdddddddddddddddddddddddddddddddddddddddssssssssssssssssssdsfdf

  warehouse:
    build: ../app/Warehouse
    container_name: warehouse-service
    image: gabbazovr/warehouselocal:latest
    hostname: warehouse-service
    restart: always
    networks:
      - shop-bridge
    depends_on:
      - postgres_db
      - rabbitmq
    environment:
     - POSTGRES_CONNECTION_STRING=Host=postgres_db;Username=postgres;Password=admin;Database=warehouse
     - SECRET=fgryrhfdjhgklossdsfsdfdddddddddddddddddddddddddddddddddddddddssssssssssssssssssdsfdf

  delivery:
    build: ../app/Delivery
    container_name: delivery-service
    image: gabbazovr/deliverylocal:latest
    hostname: delivery-service
    restart: always
    networks:
      - shop-bridge
    depends_on:
      - postgres_db
      - rabbitmq
    environment:
     - POSTGRES_CONNECTION_STRING=Host=postgres_db;Username=postgres;Password=admin;Database=warehouse
     - SECRET=fgryrhfdjhgklossdsfsdfdddddddddddddddddddddddddddddddddddddddssssssssssssssssssdsfdf

  postgres_db:
    restart: always
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Otus
    ports:
      - "5436:5432"
    networks:
      - shop-bridge
    volumes:
      - postgres-data_shop:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      # - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbit-data_shop:/var/lib/rabbitmq
      # - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15674:15672
      - 5688:5672
    networks:
      - shop-bridge

  otel-collector:
    hostname: otel-collector
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector.yaml" ]
    image: otel/opentelemetry-collector-contrib:0.133.0
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "13133:13133"
      - "1777:1777"
      - ":55679"
      - "8889:8889"
    networks:
      - shop-bridge
    depends_on:
        - apigetway
        - jaeger
        - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - shop-bridge
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata_shop:/prometheus
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - shop-bridge
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata_shop:/var/lib/grafana
    depends_on:
      - loki
      - prometheus
      - jaeger


  jaeger:
    hostname: otel-jaeger
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
    networks:
      - shop-bridge
  
  loki:
    image: grafana/loki:3.4.5
    container_name: loki
    hostname: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - shop-bridge

  redis:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - redis:/data
    networks:
      - shop-bridge

volumes:
  postgres-data_shop:
  grafanadata_shop:
  prometheusdata_shop:
  rabbit-data_shop:
  redis: