<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\application\Application\Application.csproj" />
  </ItemGroup>
  <ItemGroup>
  		<Protobuf Include="Protos\account_billing.proto" GrpcServices="Client" />

  </ItemGroup>
</Project>
