apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.servicename }}
  name: {{ .Values.servicename }}
spec:
  ports:
    - port: {{.Values.portserv}}
      protocol: TCP
      targetPort: {{.Values.targetport}}
      name: rest
    - protocol: TCP
      port: {{.Values.portservgrps}}
      targetPort: {{.Values.targetportgrps}}
      name: grps
  selector:
    app:  {{.Values.netserv}}