mode: daemonset

image:
  repository: otel/opentelemetry-collector-k8s

replicaCount: 1

presets:
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  logsCollection:
    enabled: true

config:
  exporters:
    otlp:
      endpoint: <OBSERVABILITY_BACKEND>
      

  connectors:
    spanmetrics:

  service:
    pipelines:
      traces:
        exporters: [spanmetrics, otlp]
      metrics:
        receivers: [otlp, spanmetrics]
        exporters: [otlp] 
      logs:
        exporters: [otlp]